version: 2.1
orbs:
  circleci-maven-release-orb: sonatype-nexus-community/circleci-maven-release-orb@x.y.z
workflows:
  main:
    jobs:
      - circleci-maven-release-orb/run-maven-release:
          mvn-release-perform-command: 'mvn --batch-mode release:perform -DdryRun=true -s .maven.xml
          environment:
            - GITHUB_USERNAME: josecardenas2021
            - GITHUB_EMAIL: jose.cardenas@globant.com
            - GPG_PASSPHRASE: J0s3C4rd3n4s
            - SECRING_GPG_ASC_BASE64: josecardenas2021
            - SERVER_OSSRH_PASSWORD: josecardenas2021
            - SERVER_OSSRH_USERNAME: josecardenas2021
            