version: '2.1'
orbs:
  circleci-maven-release-orb: sonatype-nexus-community/circleci-maven-release-orb@0.0.16
workflows:
  main:
    jobs:
      - circleci-maven-release-orb/run-maven-release:
          mvn-release-perform-command: "mvn --batch-mode release:perform -DdryRun=true"
          ssh-fingerprints: 'MD5:35:b1:eb:f1:2e:3d:59:0f:ea:e9:92:fc:03:76:10:0b'