version: 2.1
orbs:
  circleci-maven-release-orb: sonatype-nexus-community/circleci-maven-release-orb@0.0.16

jobs:
  release:
    executor: default
    steps:
      - circleci-maven-release-orb/run-maven-release:
          ssh-fingerprints: 'MD5:35:b1:eb:f1:2e:3d:59:0f:ea:e9:92:fc:03:76:10:0b'
      - store_test_results:
          path: test-results

workflows:
  main:
    jobs:
      - release

    