version: 2.1
orbs:
  circleci-maven-release-orb: sonatype-nexus-community/circleci-maven-release-orb@0.0.16
  slack: circleci/slack@4.1

jobs:
  notify:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - slack/notify:
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "*This is a text notification*",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
          event: always

workflows:
  release:
    jobs:
      - circleci-maven-release-orb/run-maven-release:
          ssh-fingerprints: 'MD5:35:b1:eb:f1:2e:3d:59:0f:ea:e9:92:fc:03:76:10:0b'
  post-release:
    jobs:
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/*.jar
      - notify:
          context: slack-secrets